apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: index-provider

commonLabels:
  toolkit.fluxcd.io/tenant: index-provider

resources:
  - namespace.yaml
  - flux-cd.yaml
  - flux-rbac.yaml
  - github-auth.yaml
