apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::407967248065:role/default_node_group-eks-node-group-20220326104849172600000002
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::407967248065:user/masih
      username: masih
      groups:
        - system:masters
    - userarn: arn:aws:iam::407967248065:user/marco
      username: marco
      groups:
        - system:masters
    - userarn: arn:aws:iam::407967248065:user/gammazero
      username: gammazero
      groups:
        - system:masters
    - userarn: arn:aws:iam::407967248065:user/will.scott
      username: will.scott
      groups:
        - system:masters
    - userarn: arn:aws:iam::407967248065:user/kylehuntsman
      username: kylehuntsman
      groups:
        - system:masters
