apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: promtail

resources:
  - daemonset.yaml
  - rbac.yaml

configMapGenerator:
  - name: promtail-config
    files:
      - config.yaml
