apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storetheindex
resources:
- ../../../../base/storetheindex
- ingress.yaml
- pod-monitor.yaml
- github-auth.yaml
patchesStrategicMerge:
- patch-indexer.yaml
secretGenerator:
- name: indexer-identity
  files:
  - indexer-0.key=indexer-0-identity.encrypted
  - indexer-1.key=indexer-1-identity.encrypted
configMapGenerator:
- name: indexer-config
  behavior: replace
  files:
  - config
replicas:
- name: indexer
  count: 2
images:
- name: storetheindex
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/storetheindex/storetheindex # {"$imagepolicy": "storetheindex:storetheindex:name"}
  newTag: 20220601112117-d086641cb2c3953d96f79335bbc166a3c53564e5 # {"$imagepolicy": "storetheindex:storetheindex:tag"}
