apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

resources:
  - ../../../../base/storetheindex
  - ingress.yaml
  - pod-monitor.yaml

patchesStrategicMerge:
  - patch-indexer.yaml

configMapGenerator:
  - name: indexer-env-vars
    behavior: merge
    literals:
      - STORETHEINDEX_PRIV_KEY_PATH=/identity/identity.key

secretGenerator:
  - name: indexer-identity
    files:
      - identity.key=identity.encrypted
