apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

resources:
  - ../../../../base/storetheindex
  - ingress.yaml

patchesStrategicMerge:
  - patch-indexer.yaml

secretGenerator:
  - name: indexer-identity
    files:
      - indexer-0.key=indexer-0-identity.encrypted
