apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

resources:
  - ../../../../base/storetheindex
  - ingress.yaml
  - pod-monitor.yaml

patchesStrategicMerge:
  - patch-indexer.yaml

secretGenerator:
  - name: indexer-identity
    files:
      - indexer-0.key=indexer-0-identity.encrypted

images:
  - name: storetheindex
    newName: public.ecr.aws/e2v8t0i4/storetheindex # {"$imagepolicy": "storetheindex:storetheindex:name"}
    newTag: 20220412130324-05472c8782305d2fc6761e36675088de93ecaad4 # {"$imagepolicy": "storetheindex:storetheindex:tag"}
