apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storetheindex
resources:
- ../../../../base/storetheindex
- ingress.yaml
- pod-monitor.yaml
- github-auth.yaml
patchesStrategicMerge:
- patch-indexer.yaml
secretGenerator:
- name: indexer-identity
  files:
  - indexer-0.key=indexer-0-identity.encrypted
images:
- name: storetheindex
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/storetheindex/storetheindex # {"$imagepolicy": "storetheindex:storetheindex:name"}
  newTag: 20220420092623-cc33085ff331eaf07c011261546e73d9e7cbb8f9 # {"$imagepolicy": "storetheindex:storetheindex:tag"}
