apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storetheindex
resources:
- ../../../../base/storetheindex
- ingress.yaml
- pod-monitor.yaml
- github-auth.yaml
patchesStrategicMerge:
- patch-indexer.yaml
- indexer-config.yaml
secretGenerator:
- name: indexer-identity
  files:
  - indexer-0.key=indexer-0-identity.encrypted
  - indexer-1.key=indexer-1-identity.encrypted
replicas:
- name: indexer
  count: 2
images:
- name: storetheindex
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/storetheindex/storetheindex # {"$imagepolicy": "storetheindex:storetheindex:name"}
  newTag: 20220609183015-357c23af1b6929885a2ddf7329a1537e2449b6c5 # {"$imagepolicy": "storetheindex:storetheindex:tag"}
