apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexer
spec:
  template:
    spec:
      containers:
        - name: indexer
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STORETHEINDEX_PRIV_KEY_PATH
              value: /identity/$(POD_NAME).key
          volumeMounts:
            - name: identity
              mountPath: /identity
      volumes:
        - name: identity
          secret:
            secretName: indexer-identity
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: io2
        resources:
          requests:
            storage: 5Ti
