apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexer
spec:
  template:
    spec:
      containers:
        - name: indexer
          volumeMounts:
            - name: identity
              mountPath: /identity
      volumes:
        - name: identity
          secret:
            secretName: indexer-identity
