apiVersion: v1
kind: Secret
metadata:
    name: github-auth
    namespace: storetheindex
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:otxRdj/+4Q==,iv:cYmWqtXW1Ltmk/NgOyVsSFMm10VX1EsGIrQ/rEhBcRM=,tag:x/RVDImUX0zociQhH88jaQ==,type:str]
    password: ENC[AES256_GCM,data:I7Ywv+Lax+JhcYGovXugMH/2UuvzRRRy/XIB+SejB7PB511XwzvkdA==,iv:z0hAvm7BxC97CXKNgNrNUdcAIGea++uWpVzYjZ5uQNA=,tag:ggFDUaF/SBAFwHyNmnmQLQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:407967248065:alias/sti-dev-v3-flux
          created_at: "2022-05-13T00:01:29Z"
          enc: AQICAHijN7A9DYX4tnfIrs3FJK8zcNnGPs//gerk+/dR8QTTfQGigvp7KvnYmidWyzScUAMaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEhl9Atbn+QKUqyauAgEQgDuI8EWxTciB+7HtNiWFx19nR89dtL4Vk/oXiNeTXDSnOe+iJ4UKy9QXw6qTIV0xIpMsszeK2reycEC07g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-13T00:01:29Z"
    mac: ENC[AES256_GCM,data:cGsJjYSQWFo2Dq1Cn+vzZMIvspHbPeYhiBJXXu/T+L3Ai3dzrwIi0/iirtGsFcXtkOxKtDdjVru/JYQD4MPQAjC0MMgQMzPRcZ1qTaKve2UumrEBuZhko2xJHRaIT2FcgEgBINqP3Bx51pHN9II95Th2keUeEFB7up3r1KGjhUc=,iv:Wc4Ix0XgzerlV5dXjCeM4dcFw4BoljH5aVPelpwF3ow=,tag:Q5uf7lE7XU5Sze1dXJ3rRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
