apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

resources:
  - ../../../../base/storetheindex
  - ingress.yaml
  - pod-monitor.yaml

patchesStrategicMerge:
  - patch-indexer.yaml

replicas:
  - name: indexer
    count: 2

secretGenerator:
  - name: indexer-identity
    files:
      - indexer-0.key=indexer-0-identity.encrypted
      - indexer-1.key=indexer-1-identity.encrypted

# This is to keep the production deployment unchanged as a result of base overlay changes until it 
# is automated like dev. 
images:
  - name: storetheindex
    newName: filecoin/storetheindex
    newTag: 1b16c2dd77b55cb83be99410b514068e059b952d
