---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: storetheindex
spec:
  selector:
    matchLabels:
      app: storetheindex
  endpoints:
  - port: admin
    path: /metrics
    interval: 30s
