apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storetheindex-identity
spec:
  encryptedData:
    peerid: AgCi49VyWBJUsD2IyEFl30ZqnRngUT66qjqwurvdT4Qy1Pm7yyZB4fVbWhhS/j4Z2YowgA/R+p/Z1TKH/2xAQ2HLdSCNIHPCKDMJCkaxAvFUP1XaD/hNPBTV3iK6vmmsBNdyqqHlZQEcRzkprG4yFJMR9rSPcDHYPREzWLtURZYyRznW9062VN/LKNtvs2x+mkQ5LDJYmKDSyIa1oZ9sNho06QT4McbI+m5oSttXvI/JCV7HoBH4JFFXYGS59wn5dp/FTF2lkNKhNuTaVxDgCg0Gt3LnsslSoN/aNwnp5MGhkxTiSWD+xb95L7gkR6D58dHvc/If0pvUlz0WCIkGNReOPkGfKAGE3FrFRKReVw8wHRFM1TafhjNeolO5dToO/WSUgP9HwqZ+Zt8yy4+yx2NyRrC6T5KMvmvkXq7nz4DMZDm/MjczRQ6UQVhAk3+acN07gljnJiIJ0zZNiQsjHpcs7CHoVHx0bkrPHJY9lt7OTvrHzOCpuXOjYvQlLkFMViMdNZvE7OfAxmDF8QnzaSJGq7lNyEcbdb+bfz6bqph3J2mn1n73BHijCOkYUj/WxY+vkPqp0gy8NTjoGzE79/AHRaqwNiyVU4ll9enSL3C3x7hFY/goAVkCVGp5R80m/FCNZeHbfuFLHQJ2SvQiadl6OPCdSArAGFbIlbxQh3ROcJ75UZ5dLIJfpMwzV9wjZn3pZlrFj0YUQURtb6c87nT9y7ALf283lm/BG2I5dEltAXpVvgdeQDpVC186oB/54jDeN1cGYA==
    privkey: AgBNkGN/zTTQIzkYyRg2UAdu1UPWbYkE4vGHC3jqfcgTyVguCtANpJ/sH4gxt7ZZ0XQD5MqMS2Fy2Vw58jT5JLXn4ZfJaEoGDwVdw0szVNOxVOR4fdBG/D15//E2cc1b8qL7WVxvHaVEYlnlB+26MNGkKncB5XsN9oxDX056Cem1ugd10bG6X9j2qxRiWS1BU52mo0AHYIHcGZAOCsqmWsD8pg1jEiU1iFA5VJWQkTAIBn6EF3mfLvBFGnlAl1Tt2nzbncHixkTOEXBUi4IUU5E+q4bkOpRKO+ySZuP0eBeGdJwpor27l1qCWa8+3dRKQy0PaT1Yu1v/qpmmgBNfTIviCc7e45QX4h/p8DLZDRA+gu1WeKg0Ivl6wd2AlaUWDCmFvErTSTupJs1hWrTCP/46LhdqQVMtozLh04vw48X8H/35HBmXpf4hSZJYNwK5chDgZgOa03lnS7kLz8m5HUH4Y2nIBL03Ca4piXWtGJz8OqNh47G18LFmhTM6CKfbJGxmfMNGN++YdWjPumtlc3jKxF8TAwnL8wSgZAWCiI6+pzQbXqFdooSTvuLxH3IdGEJT6jbCcrAGiyGP7zopOoEZI2DEEthF5Q1Q9b9wv3+2vjsTjpwIu5cvcIuCowW0RyDoU3hzOBz/kCTXVsiHv0qpCQe2DdbY0Qz5vNneJhPQ6mN6E0ESO3T0dn/bBq6gBWhxESo04z1cgpsLCoo+eJQ/STWKW3EY+uCyOenkl7DJ1hHmSBOsn/d5QGv7FOz407czOULwEz8eADdvTQQgNBkaR+0ZnmHKeibhisS1eWPSNmG31suyv4hyfhhsmYU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: storetheindex-identity
    type: Opaque

