---
# Source: lotus-bundle/templates/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: storetheindex-0-storetheindex
  namespace: default
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: storetheindex
      release: storetheindex-0
  endpoints:
  - port: admin
    path: /metrics
    interval: 30s
