apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

commonLabels:
  toolkit.fluxcd.io/tenant: storetheindex

resources:
  - namespace.yaml
  - flux-cd.yaml
  - flux-rbac.yaml

secretGenerator:
  - name: github-auth
    envs:
      - github-auth.env.encrypted
