apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

commonLabels:
  toolkit.fluxcd.io/tenant: storetheindex

resources:
  - namespace.yaml
  - flux-cd.yaml
  - flux-rbac.yaml
  - github-auth.yaml
  - ../../../../base/ecr-public-credentials-sync

patchesStrategicMerge:
  - sa-patch.yaml

configMapGenerator:
  - name: ecr-public-creds-sync-env
    behavior: merge
    literals:
      - ECR_REGISTRY=public.ecr.aws/e2v8t0i4/storetheindex
