apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ingress-nginx
  - kube-system
  - cert-manager
  - storetheindex
  - cluster-autoscaler
  - monitoring
  - aws-ebs-csi-driver
  - promtail
