# Publishes storetheindex container images to the public Docker Hub registry.
# See: https://hub.docker.com/r/filecoin/storetheindex
name: Docker Hub

on:
  # The tags in this repo are pushed via CI, the push events for which will not trigger workflows.
  # However, releases are created by contributors, hence the use of release event to build images.
  release:
    types:
      - published
  push:
    paths-ignore:
      - 'deploy/**'
      - 'doc/**'
    branches:
      - main

jobs:
  publisher:
    if: ${{ github.event.pusher.name != 'sti-bot' }}
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DOCKERHUB_REGISTRY: filecoin
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine Container Tag
        run: |
          IMAGE_TAG="${GITHUB_REF#refs/tags/v}"
          if test "${IMAGE_TAG}" = "${GITHUB_REF}"; then
            IMAGE_TAG="$(date '+%Y%m%d%H%M%S')-${GITHUB_SHA}"
          fi
          echo "Using image tag: ${IMAGE_TAG}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Container Image
        run: |
          IMAGE_NAME="${DOCKERHUB_REGISTRY}/storetheindex:${IMAGE_TAG}"
          docker build -t "${IMAGE_NAME}" .
          docker push "${IMAGE_NAME}"
          echo "Published image ${IMAGE_NAME}"
